using Fast.Application;
using Fast.Application.Interfaces;
using Ninject.Modules;

namespace Fast.Infra.CrossCutting.IoC
{
	public class NinjectAppServiceModule : NinjectModule
	{
		public override void Load()
		{
			Bind(typeof(IAppServiceBase)).To(typeof(AppServiceBase<>));
			Bind<IUserAppService>().To<UserAppService>();
			Bind<IEmployeeAppService>().To<EmployeeAppService>();
			Bind<IEmployeeAllAppService>().To<EmployeeAllAppService>();
			Bind<IEmployeeOvertimeAppService>().To<EmployeeOvertimeAppService>();
			Bind<IEmployeeLeaveAppService>().To<EmployeeLeaveAppService>();
			Bind<IUserLogAppService>().To<UserLogAppService>();
			Bind<IRoleAppService>().To<RoleAppService>();
			Bind<IMenuAppService>().To<MenuAppService>();
			Bind<IAccessRightAppService>().To<AccessRightAppService>();
			Bind<IReferenceAppService>().To<ReferenceAppService>();
			Bind<IReferenceDetailAppService>().To<ReferenceDetailAppService>();
			Bind<IMachineAppService>().To<MachineAppService>();
			Bind<IUserMachineAppService>().To<UserMachineAppService>();
			Bind<IUserMachineTypeAppService>().To<UserMachineTypeAppService>();
			Bind<ILocationMachineTypeAppService>().To<LocationMachineTypeAppService>();
			Bind<ISkillAppService>().To<SkillAppService>();
			Bind<ILocationAppService>().To<LocationAppService>();
			Bind<IWppAppService>().To<WppAppService>();
			Bind<IWppStpAppService>().To<WppStpAppService>();
			Bind<IMppAppService>().To<MppAppService>();
			Bind<ICalendarAppService>().To<CalendarAppService>();
			Bind<ICalendarHolidayAppService>().To<CalendarHolidayAppService>();
			Bind<IJobTitleAppService>().To<JobTitleAppService>();
			Bind<ILoggerAppService>().To<LoggerAppService>();
			Bind<IChecklistAppService>().To<ChecklistAppService>();
			Bind<IChecklistLocationAppService>().To<ChecklistLocationAppService>();
			Bind<IChecklistComponentAppService>().To<ChecklistComponentAppService>();
			Bind<IChecklistValueAppService>().To<ChecklistValueAppService>();
			Bind<IChecklistValueHistoryAppService>().To<ChecklistValueHistoryAppService>();
			Bind<IChecklistSubmitAppService>().To<ChecklistSubmitAppService>();
			Bind<IChecklistApprovalAppService>().To<ChecklistApprovalAppService>();
			Bind<IChecklistApproverAppService>().To<ChecklistApproverAppService>();
			Bind<IMppChangesAppService>().To<MppChangesAppService>();
			Bind<IWppChangesAppService>().To<WppChangesAppService>();
			Bind<IWeeksAppService>().To<WeeksAppService>();
			Bind<ILPHAppService>().To<LPHAppService>();
			Bind<ILPHApprovalsAppService>().To<LPHApprovalsAppService>();
			Bind<ILPHLocationsAppService>().To<LPHLocationsAppService>();
			Bind<ILPHComponentsAppService>().To<LPHComponentsAppService>();
			Bind<ILPHValuesAppService>().To<LPHValuesAppService>();
			Bind<ILPHExtrasAppService>().To<LPHExtrasAppService>();
			Bind<ILPHValueHistoriesAppService>().To<LPHValueHistoriesAppService>();
			Bind<ILPHSubmissionsAppService>().To<LPHSubmissionsAppService>();
			Bind<IManPowerAppService>().To<ManPowerAppService>();
			Bind<IPPLPHAppService>().To<PPLPHAppService>();
			Bind<IPPLPHApprovalsAppService>().To<PPLPHApprovalsAppService>();
			Bind<IPPLPHLocationsAppService>().To<PPLPHLocationsAppService>();
			Bind<IPPLPHComponentsAppService>().To<PPLPHComponentsAppService>();
			Bind<IPPLPHValuesAppService>().To<PPLPHValuesAppService>();
			Bind<IPPLPHExtrasAppService>().To<PPLPHExtrasAppService>();
			Bind<IPPLPHValueHistoriesAppService>().To<PPLPHValueHistoriesAppService>();
			Bind<IPPLPHSubmissionsAppService>().To<PPLPHSubmissionsAppService>();
			Bind<ITrainingAppService>().To<TrainingAppService>();
			Bind<IBrandAppService>().To<BrandAppService>();
			Bind<IBlendAppService>().To<BlendAppService>();
			Bind<IUserRoleAppService>().To<UserRoleAppService>();
			Bind<IMaterialCodeAppService>().To<MaterialCodeAppService>();
			Bind<IWppPrimAppService>().To<WppPrimAppService>();
			Bind<IBrandConversionAppService>().To<BrandConversionAppService>();
			Bind<IReportRemarksAppService>().To<ReportRemarksAppService>();
			Bind<ITrainingTitleAppService>().To<TrainingTitleAppService>();
			Bind<ITrainingTitleMachineTypeAppService>().To<TrainingTitleMachineTypeAppService>();
			Bind<IInputDailyAppService>().To<InputDailyAppService>();
			Bind<IMealRequestAppService>().To<MealRequestAppService>();
			Bind<IShuttleRequestAppService>().To<ShuttleRequestAppService>();
			Bind<IInputOVAppService>().To<InputOVAppService>();
			Bind<IMachineAllocationAppService>().To<MachineAllocationAppService>();
			Bind<IWppPrimaryAppService>().To<WppPrimaryAppService>();
			Bind<IInputTargetAppService>().To<InputTargetAppService>();
			Bind<IPPReportYieldOvsAppService>().To<PPReportYieldOvsAppService>();
			Bind<IPPReportYieldTargetsAppService>().To<PPReportYieldTargetsAppService>();
			Bind<IPPReportYieldIMLsAppService>().To<PPReportYieldIMLsAppService>();
			Bind<IPPReportYieldsAppService>().To<PPReportYieldsAppService>();
			Bind<IPPReportYieldMCDietsAppService>().To<PPReportYieldMCDietsAppService>();
			Bind<IPPReportYieldKreteksAppService>().To<PPReportYieldKreteksAppService>();
			Bind<IPPReportYieldWhitesAppService>().To<PPReportYieldWhitesAppService>();
			Bind<IReportKPICRRConversionAppService>().To<ReportKPICRRConversionAppService>();
			Bind<IReportKPIDustAppService>().To<ReportKPIDustAppService>();
			Bind<IReportKPITargetAppService>().To<ReportKPITargetAppService>();
			Bind<IReportKPIRipperInfoAppService>().To<ReportKPIRipperInfoAppService>();
			Bind<IReportKPITobaccoWeightAppService>().To<ReportKPITobaccoWeightAppService>();
			Bind<IReportKPIWorkHourAppService>().To<ReportKPIWorkHourAppService>();
			Bind<IReportKPIStickPerPackAppService>().To<ReportKPIStickPerPackAppService>();
			Bind<IReportKPICRRAppService>().To<ReportKPICRRAppService>();
			Bind<IReportKPIDIMAppService>().To<ReportKPIDIMAppService>();
			Bind<IReportKPIProdVolAppService>().To<ReportKPIProdVolAppService>();
			Bind<IReportKPIYieldAppService>().To<ReportKPIYieldAppService>();
		}
	}
}
