using Fast.Domain.Interfaces.Services;
using Fast.Domain.Services;
using Fast.Infra.Logging;
using Ninject.Modules;

namespace Fast.Infra.CrossCutting.IoC
{
	public class NinjectServiceModule : NinjectModule
	{
		public override void Load()
		{
			Bind(typeof(IServiceBase<>)).To(typeof(ServiceBase<>));
			Bind<IUserService>().To<UserService>();
			Bind<IEmployeeService>().To<EmployeeService>();
			Bind<IEmployeeAllService>().To<EmployeeAllService>();
			Bind<IEmployeeLeaveService>().To<EmployeeLeaveService>();
			Bind<IEmployeeOvertimeService>().To<EmployeeOvertimeService>();
			Bind<IUserLogService>().To<UserLogService>();
			Bind<IRoleService>().To<RoleService>();
			Bind<IAccessRightService>().To<AccessRightService>();
			Bind<IMenuServiceService>().To<MenuService>();
			Bind<IReferenceService>().To<ReferenceService>();
			Bind<IReferenceDetailService>().To<ReferenceDetailService>();
			Bind<IMachineService>().To<MachineService>();
			Bind<IUserMachineService>().To<UserMachineService>();
			Bind<IUserMachineTypeService>().To<UserMachineTypeService>();
			Bind<ILocationMachineTypeService>().To<LocationMachineTypeService>();
			Bind<ISkillService>().To<SkillService>();
			Bind<ILocationService>().To<LocationService>();
			Bind<IWppService>().To<WppService>();
			Bind<IWppStpService>().To<WppStpService>();
			Bind<IMppService>().To<MppService>();
			Bind<ICalendarService>().To<CalendarService>();
			Bind<ICalendarHolidayService>().To<CalendarHolidayService>();
			Bind<IJobTitleService>().To<JobTitleService>();
			Bind<ILoggerService>().To<Logger>();
			Bind<IChecklistService>().To<ChecklistService>();
			Bind<IChecklistLocationService>().To<ChecklistLocationService>();
			Bind<IChecklistComponentService>().To<ChecklistComponentService>();
			Bind<IChecklistValueService>().To<ChecklistValueService>();
			Bind<IChecklistValueHistoryService>().To<ChecklistValueHistoryService>();
			Bind<IChecklistSubmitService>().To<ChecklistSubmitService>();
			Bind<IChecklistApprovalService>().To<ChecklistApprovalService>();
			Bind<IChecklistApproverService>().To<ChecklistApproverService>();
			Bind<IMppChangesService>().To<MppChangesService>();
			Bind<IWppChangesService>().To<WppChangesService>();
			Bind<IWeeksService>().To<WeeksService>();
			Bind<ILPHService>().To<LPHService>();
			Bind<ILPHApprovalsService>().To<LPHApprovalsService>();
			Bind<ILPHLocationsService>().To<LPHLocationsService>();
			Bind<ILPHComponentsService>().To<LPHComponentsService>();
			Bind<ILPHValuesService>().To<LPHValuesService>();
			Bind<ILPHExtrasService>().To<LPHExtrasService>();
			Bind<ILPHValueHistoriesService>().To<LPHValueHistoriesService>();
			Bind<ILPHSubmissionsService>().To<LPHSubmissionsService>();
			Bind<IManPowerService>().To<ManPowerService>();
			Bind<IPPLPHService>().To<PPLPHService>();
			Bind<IPPLPHApprovalsService>().To<PPLPHApprovalsService>();
			Bind<IPPLPHLocationsService>().To<PPLPHLocationsService>();
			Bind<IPPLPHComponentsService>().To<PPLPHComponentsService>();
			Bind<IPPLPHValuesService>().To<PPLPHValuesService>();
			Bind<IPPLPHExtrasService>().To<PPLPHExtrasService>();
			Bind<IPPLPHValueHistoriesService>().To<PPLPHValueHistoriesService>();
			Bind<IPPLPHSubmissionsService>().To<PPLPHSubmissionsService>();
			Bind<ITrainingService>().To<TrainingService>();
			Bind<IBrandService>().To<BrandService>();
			Bind<IBlendService>().To<BlendService>();
			Bind<IUserRoleService>().To<UserRoleService>();
			Bind<IMaterialCodeService>().To<MaterialCodeService>();
			Bind<IWppPrimService>().To<WppPrimService>();
			Bind<IBrandConversionService>().To<BrandConversionService>();
			Bind<IReportRemarksService>().To<ReportRemarksService>();
			Bind<ITrainingTitleService>().To<TrainingTitleService>();
			Bind<ITrainingTitleMachineTypeService>().To<TrainingTitleMachineTypeService>();
			Bind<IInputDailyService>().To<InputDailyService>();
			Bind<IMealRequestService>().To<MealRequestService>();
			Bind<IShuttleRequestService>().To<ShuttleRequestService>();
			Bind<IInputOVService>().To<InputOVService>();
			Bind<IMachineAllocationService>().To<MachineAllocationService>();
			Bind<IWppPrimaryService>().To<WppPrimaryService>();
			Bind<IInputTargetService>().To<InputTargetService>();
			Bind<IPPReportYieldOvsService>().To<PPReportYieldOvsService>();
			Bind<IPPReportYieldTargetsService>().To<PPReportYieldTargetsService>();
			Bind<IPPReportYieldIMLsService>().To<PPReportYieldIMLsService>();
			Bind<IPPReportYieldsService>().To<PPReportYieldsService>();
			Bind<IPPReportYieldMCDietsService>().To<PPReportYieldMCDietsService>();
			Bind<IPPReportYieldKreteksService>().To<PPReportYieldKreteksService>();
			Bind<IPPReportYieldWhitesService>().To<PPReportYieldWhitesService>();
			Bind<IReportKPICRRConversionService>().To<ReportKPICRRConversionService>();
			Bind<IReportKPIDustService>().To<ReportKPIDustService>();
			Bind<IReportKPITargetService>().To<ReportKPITargetService>();
			Bind<IReportKPIRipperInfoService>().To<ReportKPIRipperInfoService>();
			Bind<IReportKPITobaccoWeightService>().To<ReportKPITobaccoWeightService>();
			Bind<IReportKPIWorkHourService>().To<ReportKPIWorkHourService>();
			Bind<IReportKPIStickPerPackService>().To<ReportKPIStickPerPackService>();
			Bind<IReportKPICRRService>().To<ReportKPICRRService>();
			Bind<IReportKPIDIMService>().To<ReportKPIDIMService>();
			Bind<IReportKPIProdVolService>().To<ReportKPIProdVolService>();
			Bind<IReportKPIYieldService>().To<ReportKPIYieldService>();
		}
	}
}
