using Fast.Application.Interfaces;
using Fast.Infra.CrossCutting.Common;
using Fast.Web.Models;
using Fast.Web.Resources;
using Fast.Web.Utils;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.draw;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fast.Web.Controllers.Master
{
	[CustomAuthorize("training")]
	public class TrainingController : BaseController<TrainingModel>
	{
		#region ::Init::
		private readonly ITrainingAppService _trainingAppService;
		private readonly ITrainingTitleAppService _trainingTitleAppService;
		private readonly ITrainingTitleMachineTypeAppService _trainingTitleMachineTypeAppService;
		private readonly IReferenceAppService _referenceAppService;
		private readonly IMenuAppService _menuService;
		private readonly ILoggerAppService _logger;
		#endregion

		#region ::Constructor::
		public TrainingController(
			ILoggerAppService logger,
			ITrainingTitleAppService trainingTitleAppService,
			ITrainingTitleMachineTypeAppService trainingTitleMachineTypeAppService,
			ITrainingAppService empOvertimeService,
			IReferenceAppService referenceAppService,
			IMenuAppService menuService)
		{
			_trainingTitleAppService = trainingTitleAppService;
			_trainingTitleMachineTypeAppService = trainingTitleMachineTypeAppService;
			_trainingAppService = empOvertimeService;
			_referenceAppService = referenceAppService;
			_menuService = menuService;
			_logger = logger;
		}
		#endregion

		#region ::Public Methods::		
		public ActionResult Index()
		{
			GetTempData();

			ViewBag.MachineTypeList = DropDownHelper.BuildMultiEmpty();

			TrainingModel model = new TrainingModel();
			model.Access = GetAccess(WebConstants.MenuSlug.TRAINING, _menuService);

			return View(model);
		}

		public ActionResult Edit(int id)
		{
			ViewBag.MachineTypeList = DropDownHelper.BindDropDownMultiMachineType(_referenceAppService);

			string training = _trainingAppService.GetById(id);
			TrainingModel trainingModel = training.DeserializeToTraining();

			return PartialView(trainingModel);
		}

		[HttpPost]
		public ActionResult Edit(TrainingModel model)
		{
			try
			{
				ViewBag.MachineTypeList = DropDownHelper.BuildMultiEmpty();

				model.Access = GetAccess(WebConstants.MenuSlug.TRAINING, _menuService);

				if (!ModelState.IsValid)
				{
					SetFalseTempData(UIResources.InvalidModelState);
					return RedirectToAction("Index");
				}

				string training = _trainingAppService.GetById(model.ID, true);
				TrainingModel trainingModel = training.DeserializeToTraining();

				trainingModel.ModifiedBy = AccountName;
				trainingModel.ModifiedDate = DateTime.Now;
				trainingModel.MachineTypeID = model.MachineTypeID;

				string data = JsonHelper<TrainingModel>.Serialize(trainingModel);

				_trainingAppService.Update(data);

				SetTrueTempData(UIResources.EditSucceed);
			}
			catch (Exception ex)
			{
				SetFalseTempData(UIResources.EditFailed);
				_logger.LogError(ex.GetAllMessages(), AccountID, AccountName);
			}

			return RedirectToAction("Index");
		}

		public ActionResult GenerateExcel()
		{
			try
			{
				// Getting all data    			
				string trainings = _trainingAppService.GetAll();
				List<TrainingModel> trainingList = trainings.DeserializeToTrainingList();

				byte[] excelData = ExcelGenerator.ExportTraining(trainingList, AccountName);

				Response.Clear();
				Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
				Response.AddHeader("content-disposition", "attachment;filename=Master-Employee-Training.xlsx");
				Response.BinaryWrite(excelData);
				Response.End();
			}
			catch (Exception ex)
			{
				SetFalseTempData(UIResources.GenerateFailed);
				_logger.LogError(ex.GetAllMessages(), AccountID);
			}

			return RedirectToAction("Index");
		}

		public ActionResult GeneratePDF()
		{
			try
			{
				// Getting all data    			
				string trainings = _trainingAppService.GetAll();
				List<TrainingModel> trainingList = trainings.DeserializeToTrainingList();

				Document pdfDoc = new Document(PageSize.A3.Rotate(), 10, 10, 10, 10);
				PdfWriter pdfWriter = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
				pdfDoc.Open();

				Image image = Image.GetInstance(Server.MapPath("~/Content/theme/images/fast-blue.jpg"));
				image.ScaleAbsolute(193, 38);
				pdfDoc.Add(image);

				BaseFont bf = BaseFont.CreateFont(BaseFont.TIMES_ROMAN, BaseFont.CP1252, BaseFont.EMBEDDED);
				Font font = new Font(bf, 12);
				pdfDoc.Add(new Paragraph(new Chunk("Title          : Master Employee Training", font)));
				pdfDoc.Add(new Paragraph(new Chunk("Generated By   : " + AccountName, font)));
				pdfDoc.Add(new Paragraph(new Chunk("Generated Date : " + DateTime.Now.ToString("dd-MMM-yy HH:mm:ss"), font)));

				//Horizontal Line
				Paragraph line = new Paragraph(new Chunk(new LineSeparator(0.0F, 100.0F, Color.BLACK, Element.ALIGN_LEFT, 1)));
				pdfDoc.Add(line);

				//Table
				PdfPTable table = new PdfPTable(12);
				table.WidthPercentage = 100;
				//0=Left, 1=Centre, 2=Right
				table.HorizontalAlignment = 0;
				table.SpacingBefore = 20f;
				table.SpacingAfter = 30f;

				PdfPCell cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				Chunk chunk = new Chunk("Emp ID");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Emp Name");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Position");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Department");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("BU");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Base Location");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Category");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Title");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Start - End Date");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Trainer");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Score");
				cell.AddElement(chunk);
				table.AddCell(cell);

				cell = new PdfPCell();
				cell.BackgroundColor = Color.GRAY;
				chunk = new Chunk("Status");
				cell.AddElement(chunk);
				table.AddCell(cell);

				foreach (var item in trainingList)
				{
					table.AddCell(item.EmployeeID);
					table.AddCell(item.FullName);
					table.AddCell(item.Position);
					table.AddCell(item.Department);
					table.AddCell(item.BU);
					table.AddCell(item.BasetownLocation);
					table.AddCell(item.TrainingCategory);
					table.AddCell(item.TrainingTitle);
					string startendDate = (item.StartDate.HasValue ? item.StartDate.Value.ToString("dd-MMM-yy") : string.Empty) + " - " + (item.EndDate.HasValue ? item.EndDate.Value.ToString("dd-MMM-yy") : string.Empty);
					table.AddCell(startendDate);
					table.AddCell(item.Trainer);
					table.AddCell(item.Score);
					table.AddCell(item.StatusTraining);
				}

				pdfDoc.Add(table);
				pdfWriter.CloseStream = false;
				pdfDoc.Close();

				Response.Buffer = true;
				Response.ContentType = "application/pdf";
				Response.AddHeader("content-disposition", "attachment;filename=Master-Employee-Training.pdf");
				Response.Cache.SetCacheability(HttpCacheability.NoCache);
				Response.Write(pdfDoc);
				Response.End();
			}
			catch (Exception ex)
			{
				SetFalseTempData(UIResources.GenerateFailed);
				_logger.LogError(ex.GetAllMessages(), AccountID);
			}

			return RedirectToAction("Index");
		}

		[HttpPost]
		public ActionResult GetAll()
		{
			try
			{
				var draw = Request.Form.GetValues("draw").FirstOrDefault();
				var start = Request.Form.GetValues("start").FirstOrDefault();
				var length = Request.Form.GetValues("length").FirstOrDefault();
				var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
				var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
				var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

				// Paging Size (10,20,50,100)    
				int pageSize = length != null ? Convert.ToInt32(length) : 0;
				int skip = start != null ? Convert.ToInt32(start) : 0;

				// Getting all data    			
				string trainings = _trainingAppService.GetAll();
				List<TrainingModel> trainingList = trainings.DeserializeToTrainingList();

				int recordsTotal = trainingList.Count();

				bool isLoaded = false;

				sortColumn = sortColumn == "ID" ? "" : sortColumn;

				if (!string.IsNullOrEmpty(searchValue) || !string.IsNullOrEmpty(sortColumn))
				{
					isLoaded = true;
					Dictionary<long, string> machineTypeMap = new Dictionary<long, string>();
					foreach (var item in trainingList)
					{
						if (item.MachineTypeID.HasValue)
						{
							if (machineTypeMap.ContainsKey(item.MachineTypeID.Value))
							{
								string mt;
								machineTypeMap.TryGetValue(item.MachineTypeID.Value, out mt);
								item.MachineType = mt;
							}
							else
							{
								item.MachineType = GetTrainingMachineType(item.TrainingTitle);
								machineTypeMap.Add(item.MachineTypeID.Value, item.MachineType);
							}
						}
					}
				}

				// Search    
				if (!string.IsNullOrEmpty(searchValue))
				{
					trainingList = trainingList.Where(m => m.EmployeeID != null && m.EmployeeID.ToLower().Contains(searchValue.ToLower()) ||
														   m.FullName != null && m.FullName.ToLower().Contains(searchValue.ToLower()) ||
														   m.Position != null && m.Position.ToLower().Contains(searchValue.ToLower()) ||
														   m.Department != null && m.Department.ToLower().Contains(searchValue.ToLower()) ||
														   m.BU != null && m.BU.ToLower().Contains(searchValue.ToLower()) ||
														   m.TrainingCategory != null && m.TrainingCategory.ToLower().Contains(searchValue.ToLower()) ||
														   m.TrainingTitle != null && m.TrainingTitle.ToLower().Contains(searchValue.ToLower()) ||
														   m.Trainer != null && m.Trainer.ToLower().Contains(searchValue.ToLower()) ||
														   m.StatusTraining != null && m.StatusTraining.ToLower().Contains(searchValue.ToLower()) ||
														   m.MachineType != null && m.MachineType.ToLower().Contains(searchValue.ToLower())).ToList();
				}

				if (!string.IsNullOrEmpty(sortColumn))
				{
					if (sortColumnDir == "asc")
					{
						switch (sortColumn.ToLower())
						{
							case "employeeid":
								trainingList = trainingList.OrderBy(x => x.EmployeeID).ToList();
								break;
							case "fullname":
								trainingList = trainingList.OrderBy(x => x.FullName).ToList();
								break;
							case "position":
								trainingList = trainingList.OrderBy(x => x.Position).ToList();
								break;
							case "department":
								trainingList = trainingList.OrderBy(x => x.Department).ToList();
								break;
							case "bu":
								trainingList = trainingList.OrderBy(x => x.BU).ToList();
								break;
							case "trainingcategory":
								trainingList = trainingList.OrderBy(x => x.TrainingCategory).ToList();
								break;
							case "trainingtitle":
								trainingList = trainingList.OrderBy(x => x.TrainingTitle).ToList();
								break;
							case "startdate":
								trainingList = trainingList.OrderBy(x => x.StartDate).ToList();
								break;
							case "enddate":
								trainingList = trainingList.OrderBy(x => x.EndDate).ToList();
								break;
							case "trainer":
								trainingList = trainingList.OrderBy(x => x.Trainer).ToList();
								break;
							case "statustraining":
								trainingList = trainingList.OrderBy(x => x.StatusTraining).ToList();
								break;
							case "score":
								trainingList = trainingList.OrderBy(x => x.Score).ToList();
								break;
							case "machinetype":
								trainingList = trainingList.OrderBy(x => x.MachineType).ToList();
								break;
							default:
								break;
						}
					}
					else
					{
						switch (sortColumn.ToLower())
						{
							case "employeeid":
								trainingList = trainingList.OrderByDescending(x => x.EmployeeID).ToList();
								break;
							case "fullname":
								trainingList = trainingList.OrderByDescending(x => x.FullName).ToList();
								break;
							case "position":
								trainingList = trainingList.OrderByDescending(x => x.Position).ToList();
								break;
							case "department":
								trainingList = trainingList.OrderByDescending(x => x.Department).ToList();
								break;
							case "bu":
								trainingList = trainingList.OrderByDescending(x => x.BU).ToList();
								break;
							case "trainingcategory":
								trainingList = trainingList.OrderByDescending(x => x.TrainingCategory).ToList();
								break;
							case "trainingtitle":
								trainingList = trainingList.OrderByDescending(x => x.TrainingTitle).ToList();
								break;
							case "startdate":
								trainingList = trainingList.OrderByDescending(x => x.StartDate).ToList();
								break;
							case "enddate":
								trainingList = trainingList.OrderByDescending(x => x.EndDate).ToList();
								break;
							case "trainer":
								trainingList = trainingList.OrderByDescending(x => x.Trainer).ToList();
								break;
							case "statustraining":
								trainingList = trainingList.OrderByDescending(x => x.StatusTraining).ToList();
								break;
							case "score":
								trainingList = trainingList.OrderByDescending(x => x.Score).ToList();
								break;
							case "machinetype":
								trainingList = trainingList.OrderByDescending(x => x.MachineType).ToList();
								break;
							default:
								break;
						}
					}
				}

				// total number of rows count     
				int recordsFiltered = trainingList.Count();

				// Paging     
				var data = trainingList.Skip(skip).Take(pageSize).ToList();

				if (!isLoaded)
				{
					Dictionary<long, string> machineTypeMap = new Dictionary<long, string>();
					foreach (var item in data)
					{
						if (item.MachineTypeID.HasValue)
						{
							if (machineTypeMap.ContainsKey(item.MachineTypeID.Value))
							{
								string mt;
								machineTypeMap.TryGetValue(item.MachineTypeID.Value, out mt);
								item.MachineType = mt;
							}
							else
							{
								item.MachineType = GetTrainingMachineType(item.TrainingTitle);
								machineTypeMap.Add(item.MachineTypeID.Value, item.MachineType);
							}
						}
					}
				}

				// Returning Json Data    
				return Json(new { data, recordsFiltered, recordsTotal, draw }, JsonRequestBehavior.AllowGet);
			}
			catch (Exception ex)
			{
				ViewBag.Result = false;
				ViewBag.ErrorMessage = UIResources.LoadDataFailed;

				_logger.LogError(ex.GetAllMessages(), AccountID);

				return Json(new { data = new List<TrainingModel>() }, JsonRequestBehavior.AllowGet);
			}
		}

		private string GetTrainingMachineType(string trainingTitle)
		{
			ICollection<QueryFilter> filters = new List<QueryFilter>();
			filters.Add(new QueryFilter("Title", trainingTitle, Operator.Contains));
			string trainingTitles = _trainingTitleAppService.Get(filters);
			TrainingTitleModel trainingTitleModel = trainingTitles.DeserializeToTrainingTitle();

			string trainginMT = _trainingTitleMachineTypeAppService.FindBy("TrainingTitleID", trainingTitleModel.ID);
			List<TrainingTitleMachineTypeModel> trainingMTList = trainginMT.DeserializeToTrainingTitleMachineTypeList();

			string result = "";

			if (trainingMTList.Count > 0)
			{
				string refMachineTypeList = _referenceAppService.FindDetailBy("ReferenceID", ((int)ReferenceEnum.MachineType).ToString(), true);
				List<ReferenceDetailModel> refMachineTypeModelList = refMachineTypeList.DeserializeToRefDetailList();

				List<string> machineTypeList = new List<string>();
				foreach (var item in trainingMTList)
				{
					var temp = refMachineTypeModelList.Where(x => x.ID == item.MachineTypeID).FirstOrDefault();
					if (temp != null)
					{
						machineTypeList.Add(temp.Code);
					}
				}

				result = string.Join(",", machineTypeList);
			}

			return result;
		}
		#endregion

		#region ::Private Methods::
		private string GetMachineType(long machineTypeID)
		{
			string machineType = _referenceAppService.GetDetailById(machineTypeID, true);
			ReferenceDetailModel machineTypeModel = machineType.DeserializeToRefDetail();

			return machineTypeModel.Code;
		}
		#endregion
	}
}
